easy_admin:
  site_name: '%app_sitename%'
  #list:
  entities:
    # List the entity class name you want to manage
    - App\Entity\Project\Projects
    - App\Entity\Product\Products
    - App\Entity\Order\Orders
    - App\Entity\Category\Categories
    - App\Entity\Review\ProjectReviews
    - App\Entity\Review\ProductReviews
    - App\Entity\Vendor\Vendors
    - App\Entity\Vendor\Vendors
    - App\Entity\Event\Events



