parameters:
  # Meta Data
  app_name: '...iSponsor!'
  app_version: '0.0.0'
  app_domain: 'smartresponsor.com'
  #
  # Redirect routs
  app_schema: 'https'
  app_homepage_route: homepage
  app_login_route: login
  app_logout_route: logout
  app_default_target_path: profile
  app_logged_out_target_route: homepage
  # Localisation
  google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
  app_locales: en|ru|uk
  #    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN|bg|tr|lt
  app_locale: 'en'
  app_locale_filter: 'en-US'
  # Cache
  app_cache: 0
  app_cache_time: 360
  # GPT
  app_gpt_consulter: '%env(GPT_API_SECRET)%'
  app_gpt_url: '%env(GPT_API_URL)%'
  # Mailing
  app_email_sender: 'taa0662621456@gmail.com'
  app_email_sender_name: '...iSponsor! Marketing America Corporation'
  app_notification_email_sender: 'taa0662621456@gmail.com'
  app_property: 'email'
  # Akismet
  app_akismet_key: 'weqweqweDFDFDFFDwqeqwewqewqe'
  # CSRF
  app_csrf_token: 'weqweqweDFDFDFFDwqeqwewqewqe'
  # Other parameters
  app_homepage_number_of_items: 10
  app_logo_url: '/favicon.ico'
  # Media folders parameters
  app_category_images_directory: '%env(APP_CATEGORY_IMAGE_DIRECTORY)%'
  app_menu_images_directory: '%env(APP_MENU_IMAGE_DIRECTORY)%'
  app_project_images_directory: '%env(APP_PROJECT_IMAGE_DIRECTORY)%'
  app_product_images_directory: '%env(APP_PRODUCT_IMAGE_DIRECTORY)%'
  app_event_images_directory: '%env(APP_EVENT_IMAGE_DIRECTORY)%'
  app_google_recaptcha: '%env(RECAPTCHA3_ENABLED)%'
  app_google_scope: '%env(RECAPTCHA_SCOPE)%'
  app_google_recaptcha_key: '%env(GOOGLE_RECAPTCHA_KEY)%'
  app_google_recaptcha_secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'
  app_vendor_images_directory: '%env(APP_VENDOR_IMAGES_DIRECTORY)%'
  # Mercure
  app_mercure_secret_key: '%env(MERCURE_SECRET_KEY)%'
  app_secret: '%env(APP_SECRET)%'






#  app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN|bg|tr|lt
#  app_cache: 0
#  app_cache_time: 360
#
#  app_homepage_number_of_items: 10





  app_offline: '0'
  app_offline_message: 'Сайт закрыт на техническое обслуживание.<br />Пожалуйста, зайдите позже.'
  app_display_offline_message: '1'
  app_offline_image: ''
  app_sitename: '...ISponsor!'
  app_editor: 'tinymce'
  app_captcha: '0'
  app_list_limit: '20'
  app_access: '1'
  app_debug: '0'
  app_debug_lang: '0'
  app_dbtype: 'mysqli'
  app_host: 'localhost'
  app_user: ''
  app_password: ''
  app_db: ''
  app_dbprefix: ''
  app_live_site: 'https://smartresponsor.com'
  app_gzip: '0'
  app_error_reporting: 'none'
  app_help_url: 'https://help.smartesponsor.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}'
  app_doc_url: 'https://doc.smartesponsor.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}'
  app_ftp_host: ''
  app_ftp_port: ''
  app_ftp_user: ''
  app_ftp_pass: ''
  app_ftp_root: ''
  app_ftp_enable: '0'
  app_offset: 'UTC'
  app_mailonline: '1'
  app_mailer: 'mail'
  app_mailfrom: 'taa0662621456@smartresponsor.com'
  app_fromname: '...I Sponsor! - crowdfunding platform'
  app_sendmail: '/usr/sbin/sendmail'
  app_smtpauth: '0'
  app_smtpuser: ''
  app_smtppass: ''
  app_smtphost: 'localhost'
  app_smtpsecure: 'none'
  app_smtpport: '25'
  app_caching: '1'
  app_cache_handler: 'file'
  app_cachetime: '15'
  app_cache_platformprefix: '1'
  app_MetaDesc: 'альтернатива Kickstarter, Indiegogo, Planeta, Bigidea. Площадка краудфандинга и фандрайзинга.'
  app_MetaKeys: 'krowdfunding, fundraising, спільнокошт, велика ідея, спонсор, инвестор, стартап, ico'
  app_MetaTitle: '1'
  app_MetaAuthor: '0'
  app_MetaVersion: '0'
  app_robots: 'index, nofollow'
  app_sef: '1'
  app_sef_rewrite: '1'
  app_sef_suffix: '0'
  app_unicodeslugs: '0'
  app_feed_limit: '10'
  app_feed_email: 'none'
  app_log_path: '/var/www/k924/data/www/smartresponsor-secret/administrator/logs'
  app_tmp_path: '/var/www/k924/data/www/smartresponsor-secret/tmp'
  app_lifetime: '15'
  app_session_handler: 'none'
  app_shared_session: '0'
  app_memcache_persist: '1'
  app_memcache_compress: '0'
  app_memcache_server_host: 'localhost'
  app_memcache_server_port: '11211'
  app_memcached_persist: '1'
  app_memcached_compress: '0'
  app_memcached_server_host: 'localhost'
  app_memcached_server_port: '11211'
  app_redis_persist: '1'
  app_redis_server_host: 'localhost'
  app_redis_server_port: '6379'
  app_redis_server_auth: ''
  app_redis_server_db: '0'
  app_proxy_enable: '0'
  app_proxy_host: ''
  app_proxy_port: ''
  app_proxy_user: ''
  app_proxy_pass: ''
  app_massmailoff: '1'
  app_reply_to: 'taa0662621456@smartresponsor.com'
  app_reply_to_name: '...I Sponsor!'
  app_MetaRights: ''
  app_force_ssl: '2'
  app_session_memcache_server_host: 'localhost'
  app_session_memcache_server_port: '11211'
  app_session_memcached_server_host: 'localhost'
  app_session_memcached_server_port: '11211'
  app_cookie_domain: '.smartresponsor.com'
  app_cookie_path: ''
  app_asset_id: '1'
  app_session_redis_persist: '1'
  app_session_redis_server_host: 'localhost'
  app_session_redis_server_port: '6379'
  app_session_redis_server_auth: ''
  app_session_redis_server_db: '0'
  app_debug_lang_const: '1'

